// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqfxzjuqjjdnmoaenore.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxZnh6anVxampkbm1vYWVub3JlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMTMzMjEsImV4cCI6MjA2MTg4OTMyMX0.ZuPBvFfKPqENNxZQuuUD3zlIDaYOXd78QuY0poEsKRU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);